matrix:
  include:
  - os: linux
    language: python
    python: 2.7
    sudo: false
cache:
  directories:
  - $HOME/.cache/pip
before_install:
- python --version
- pip install --upgrade pip virtualenv
- pip --version
- virtualenv ${HOME}/INSTALL
install:
- source ${HOME}/INSTALL/bin/activate && pip install psutil
- find ${HOME}/INSTALL -type f -exec md5sum {} + > ${HOME}/md5s.install
script: echo test
# If the deploy script fails, you will need to move it into the script section
# above to debug it:
deploy:
  provider: script
  script: travis/deploy.sh
  on:
    branch: travis-bug-report
addons:
  apt:
    packages:
    - python-dev

