language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/protobuf
python:
  - "2.7"
before_install: /bin/bash travis/install_protobuf.sh
env:
  - PROTOC="${HOME}/protobuf/bin/protoc"
install:
  - pip install --upgrade pip wheel setuptools
  - pip install -e .
  - pip install -e grr/config/grr-response-server/
  - pip install -e grr/config/grr-response-test/
  - python makefile.py
  - cd grr/artifacts && python makefile.py && cd -
script: grr_run_tests --processes=2
addons:
  apt:
    packages:
    - libffi-dev
    - libssl-dev
    - python-dev
    - prelink
deploy:
  - grr_client_build build --output built_templates

