language: python
python:
- '2.7'
sudo: false
matrix:
  include:
  - os: linux
  - os: osx
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/protobuf
  - $HOME/google-cloud-sdk
before_install:
- /bin/bash travis/install_protobuf.sh
env:
# From https://goo.gl/XuEMpi GCP CD with travis
- PROTOC="${HOME}/protobuf/bin/protoc" PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
install:
- pip install --upgrade pip wheel setuptools
- pip install -e .
- pip install -e grr/config/grr-response-server/
- pip install -e grr/config/grr-response-test/
- python makefile.py
- cd grr/artifacts && python makefile.py && cd -
script: grr_run_tests --processes=2
script: echo test
# If the deploy script fails, you will need to move it into the script section
# above to debug it:
# https://github.com/travis-ci/dpl/issues/477
deploy:
  provider: script
  script: travis/deploy_to_gcs.sh
  on:
    branch: travis-testing
addons:
  apt:
    packages:
    - libffi-dev
    - libssl-dev
    - python-dev
    - prelink

