matrix:
  include:
  - os: linux
    language: python
    python: 2.7
    sudo: false
    # From https://goo.gl/XuEMpi GCP CD with travis
    env: PROTOC="${HOME}/protobuf/bin/protoc" PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - os: osx
    osx_image: beta-xcode6.2
    language: generic
    python: 2.7
    sudo: required
    env: PROTOC="${HOME}/protobuf/bin/protoc" PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/protobuf
  - $HOME/Library/Caches/Homebrew
before_install:
- /bin/bash travis/install_protobuf.sh
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && git clone https://github.com/MacPython/terryfy && source terryfy/travis_tools.sh; get_python_environment macpython 2.7.11 && brew install libffi; fi
- python --version; pip --version
- pip install --upgrade pip virtualenv
- virtualenv ${HOME}/INSTALL
install:
- /bin/bash travis/install.sh
- /bin/bash travis/deploy_to_gcs.sh
#script: grr_run_tests --processes=2
script: echo test
addons:
  apt:
    packages:
    - libffi-dev
    - libssl-dev
    - python-dev
    - prelink

