language: python
sudo: false
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/protobuf
python:
- '2.7'
before_install:
- /bin/bash travis/install_protobuf.sh
env:
# From https://goo.gl/XuEMpi GCP CD with travis
- PROTOC="${HOME}/protobuf/bin/protoc" PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
install:
#- pip install --upgrade pip wheel setuptools
#- pip install -e .
#- pip install -e grr/config/grr-response-server/
#- pip install -e grr/config/grr-response-test/
#- python makefile.py
#- cd grr/artifacts && python makefile.py && cd -
#script: grr_run_tests --processes=2
script:
#- grr_client_build build --output built_templates
- wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-116.0.0-linux-x86_64.tar.gz && tar zxvf google-cloud-sdk-116.0.0-linux-x86_64.tar.gz -C ${HOME}
- mkdir built_templates && echo test${TRAVIS_BUILD_NUMBER} > built_templates/test
# See https://docs.travis-ci.com/user/encrypting-files/
- openssl aes-256-cbc -K $encrypted_03f64f0078dc_key -iv $encrypted_03f64f0078dc_iv
  -in travis/travis_uploader_service_account.json.enc -out travis/travis_uploader_service_account.json
  -d
- gcloud auth activate-service-account --key-file travis/travis_uploader_service_account.json
- gsutil -m cp built_templates/* gs://autobuilds.grr-response.com/${TRAVIS_BUILD_NUMBER}/
- shred -u travis/travis_uploader_service_account.json
addons:
  apt:
    packages:
    - libffi-dev
    - libssl-dev
    - python-dev
    - prelink
after_success:

